import '../models/node_template.dart';
import '../models/probe_result.dart';

/// Clash Meta / mihomo YAML built from ranked entry IPs + one tunnel template.
String buildClashSubscription({
  required List<ProbeResult> ranked,
  required NodeTemplate template,
  String remarksPrefix = 'Home',
}) {
  final proxies = <String>[];
  final names = <String>[];
  var i = 0;
  for (final r in ranked.where((e) => e.success)) {
    i += 1;
    final name = _safeName('$remarksPrefix-${r.ip}-${r.latencyMs}ms', i);
    names.add(name);
    proxies.add(_proxyYaml(name: name, ip: r.ip, template: template));
  }

  final groupNames = names.isEmpty ? '      - DIRECT\n' : names.map((n) => '      - $n').join('\n');
  return '''
# Generated by CF Prefer Refresh — debug/export only.
# Clash should normally keep using your Cloudflare edgetunnel /sub URL.
proxies:
${proxies.isEmpty ? '  []\n' : proxies.join('\n')}
proxy-groups:
  - name: PROXY
    type: select
    proxies:
$groupNames
rules:
  - MATCH,PROXY
''';
}

String _safeName(String raw, int index) {
  final cleaned = raw.replaceAll(RegExp(r'[^\w\-\.\u4e00-\u9fff]+'), '_');
  if (cleaned.isEmpty) return 'CF-$index';
  return cleaned;
}

String _yamlQuote(String value) {
  if (value.contains(':') ||
      value.contains('#') ||
      value.contains('{') ||
      value.contains('?') ||
      value.contains(' ') ||
      value.contains('*')) {
    return "'${value.replaceAll("'", "''")}'";
  }
  return value;
}

String _proxyYaml({
  required String name,
  required String ip,
  required NodeTemplate template,
}) {
  final type = template.protocol.toLowerCase() == 'trojan' ? 'trojan' : 'vless';
  final authKey = type == 'trojan' ? 'password' : 'uuid';
  final host = template.effectiveHostHeader;
  final path = template.path.isEmpty ? '/' : template.path;
  final buf = StringBuffer()
    ..writeln('  - name: ${_yamlQuote(name)}')
    ..writeln('    type: $type')
    ..writeln('    server: $ip')
    ..writeln('    port: ${template.port}')
    ..writeln('    $authKey: ${_yamlQuote(template.uuidOrPassword)}')
    ..writeln('    network: ${template.network}')
    ..writeln('    udp: true')
    ..writeln('    tls: ${template.tls}')
    ..writeln('    servername: ${_yamlQuote(template.hostSni)}')
    ..writeln('    client-fingerprint: ${template.fingerprint}');
  if (template.network.toLowerCase() == 'ws') {
    buf
      ..writeln('    ws-opts:')
      ..writeln('      path: ${_yamlQuote(path)}')
      ..writeln('      headers:')
      ..writeln('        Host: ${_yamlQuote(host)}');
  }
  return buf.toString().trimRight();
}
